import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { RemnawaveClient } from '../client/index.js';
import { registerUserTools } from './users.js';
import { registerNodeTools } from './nodes.js';
import { registerHostTools } from './hosts.js';
import { registerSystemTools } from './system.js';
import { registerSubscriptionTools } from './subscriptions.js';
import { registerInboundTools } from './inbounds.js';
import { registerSquadTools } from './squads.js';
import { registerHwidTools } from './hwid.js';
import { registerApiTokenTools } from './api-tokens.js';
import { registerKeygenTools } from './keygen.js';
import { registerInfraBillingTools } from './infra-billing.js';
import { registerSnippetTools } from './snippets.js';
import { registerExternalSquadTools } from './external-squads.js';
import { registerSettingsTools } from './settings.js';
import { registerSubPageConfigTools } from './subscription-page-configs.js';
import { registerNodePluginTools } from './node-plugins.js';
import { registerConnectionTools } from './connections.js';
import { registerBandwidthTools } from './bandwidth.js';
import { registerNodeIntegrationTools } from './node-integrations.js';
import { registerMetadataTools } from './metadata.js';

export function registerAllTools(server: McpServer, client: RemnawaveClient) {
    registerUserTools(server, client);
    registerNodeTools(server, client);
    registerHostTools(server, client);
    registerSystemTools(server, client);
    registerSubscriptionTools(server, client);
    registerInboundTools(server, client);
    registerSquadTools(server, client);
    registerHwidTools(server, client);
    registerApiTokenTools(server, client);
    registerKeygenTools(server, client);
    registerInfraBillingTools(server, client);
    registerSnippetTools(server, client);
    registerExternalSquadTools(server, client);
    registerSettingsTools(server, client);
    registerSubPageConfigTools(server, client);
    registerNodePluginTools(server, client);
    registerConnectionTools(server, client);
    registerBandwidthTools(server, client);
    registerNodeIntegrationTools(server, client);
    registerMetadataTools(server, client);
}
